# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_routing_pb2 as grpc__routing__pb2


class RoutingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFeatures = channel.unary_stream(
                '/Routing/GetFeatures',
                request_serializer=grpc__routing__pb2.NoneLike.SerializeToString,
                response_deserializer=grpc__routing__pb2.Feature.FromString,
                )


class RoutingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoutingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFeatures': grpc.unary_stream_rpc_method_handler(
                    servicer.GetFeatures,
                    request_deserializer=grpc__routing__pb2.NoneLike.FromString,
                    response_serializer=grpc__routing__pb2.Feature.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Routing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Routing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Routing/GetFeatures',
            grpc__routing__pb2.NoneLike.SerializeToString,
            grpc__routing__pb2.Feature.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
